# Generated by Django 5.1.4 on 2026-08-22 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockDisposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('reason', models.CharField(choices=[('expired', 'Expired'), ('spoiled', 'Spoiled'), ('damaged', 'Damaged'), ('other', 'Other')], default='expired', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('disposed_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disposals', to='core.stockbatch')),
                ('disposed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disposals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-disposed_at', '-id'],
            },
        ),
    ]
