# Generated by Django 5.1.4 on 2026-09-03 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='auto_reorder',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('placed', 'Placed'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='placed', max_length=10)),
                ('auto_generated', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='core.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='core.supplier')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
