# Generated by Django 5.1.4 on 2026-09-05 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_invoice_number_and_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockbatch',
            name='disposal_note',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='disposed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='disposed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disposed_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='disposed_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
