# Generated by Django 5.1.4 on 2026-09-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_lowstockalertstate_notificationoutbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='security_answer',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='user',
            name='security_question',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
